language: ruby
rvm:
  - 2.3.1

install: 
  - gem install jekyll 
  - bundle install

script: bundle exec jekyll build --config _config.yml

deploy:
  provider: s3
  access_key_id: <%= ENV['S3_ACCESS_KEY_ID'] %>
  secret_access_key: <%= ENV['S3_SECRET_KEY'] %>
  bucket: fullstacknights.com
  skip_cleanup: true
  acl: public_read
  region: us-east-1
  local_dir: _site
  on: master

sudo: false